# Generated by Django 6.0.6 on 2026-06-29 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payer',
            old_name='color_code',
            new_name='color',
        ),
    ]
