# Generated by Django 6.0.6 on 2026-07-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_rename_color_code_payer_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='price',
        ),
        migrations.AddField(
            model_name='transaction',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='unit',
            field=models.CharField(blank=True, choices=[('kg', 'Kg'), ('ltr', 'Ltr'), ('pcs', 'Pcs'), ('pkt', 'Pkt')], max_length=5, null=True),
        ),
    ]
