# Generated by Django 6.0.6 on 2026-07-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_rename_amount_transaction_price_transaction_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(blank=True, choices=[('', '— (No Unit)'), ('Kg', 'Kg'), ('Pcs', 'Pcs'), ('Pkt', 'Pkt'), ('Ltr', 'Ltr')], default='', max_length=5),
        ),
    ]
