# Generated by Django 6.0.6 on 2026-07-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_remove_transaction_unit_alter_item_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(blank=True, choices=[('', '-'), ('Kg', 'Kg'), ('Pcs', 'Pcs'), ('Pkt', 'Pkt'), ('Ltr', 'Ltr')], default='', max_length=5),
        ),
    ]
