# Generated by Django 6.0.6 on 2026-07-07 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_alter_item_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StagingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_idx', models.IntegerField()),
                ('date', models.CharField(max_length=20)),
                ('item_name', models.CharField(blank=True, max_length=255)),
                ('item_id', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('payer_name', models.CharField(blank=True, max_length=255)),
                ('payer_id', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
