# Generated by Django 6.0.7 on 2026-07-19 14:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_stagingtransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['user', 'name'], name='expenses_it_user_id_4540ba_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['category'], name='expenses_it_categor_57b005_idx'),
        ),
        migrations.AddIndex(
            model_name='payer',
            index=models.Index(fields=['user', 'name'], name='expenses_pa_user_id_e3133b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'date'], name='expenses_tr_user_id_228bc5_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'item'], name='expenses_tr_user_id_2ba971_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'payer'], name='expenses_tr_user_id_ea256a_idx'),
        ),
    ]
